INSERT INTO MY_EMPLOYEES (ID, LAST_NAME, FIRST_NAME, USERID, SALARY) VALUES (3, 'Biri', 'Ben', 'bbiri', 1100);
INSERT INTO MY_EMPLOYEES (ID, LAST_NAME, FIRST_NAME, USERID, SALARY) VALUES (4, 'Newman', 'Chad', 'cnewman', 750);
INSERT INTO MY_EMPLOYEES (ID, LAST_NAME, FIRST_NAME, USERID, SALARY) VALUES (5, 'Rpeburn', 'Audrey', 'aroper', 1550);
