ALTER SESSION SET NLS_LANGUAGE=American;
ALTER SESSION SET NLS_TERRITORY=America;

INSERT INTO TITLE(TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE) VALUES(TITLE_ID_SEQ.NEXTVAL, 'Willie and Christmas Too', 'Willieの友達はみなサンタに宛てたクラスマスに欲しいもののリストを作りましたが、Willieだけはまだ自分のリストを作っていません。', 'G', 'CHILD', '05-OCT-2015');

INSERT INTO TITLE(TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE) VALUES(TITLE_ID_SEQ.NEXTVAL, 'Alien Again', 'SFの世界の物語です。ヒロインは惑星をエイリアンから守ることができるでしょうか。', 'R', 'SCIFI', '19-MAY-2016');

INSERT INTO TITLE(TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE) VALUES(TITLE_ID_SEQ.NEXTVAL, 'The Glob', '隕石がアメリカの小さな町に落下し、肉食性の地球外生物が放たれる古典的作品。', 'NR', 'SCIFI', '12-AUG-2016');

INSERT INTO TITLE(TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE) VALUES(TITLE_ID_SEQ.NEXTVAL, 'My Day Off', '学校をさぼってニューヨークに出かけて若者が、運と知恵を使って1日を切り抜ける姿をえがきます。', 'PG', 'COMEDY', '12-JUL-2017');

INSERT INTO TITLE(TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE) VALUES(TITLE_ID_SEQ.NEXTVAL, 'Miracles on Ice', 'サンタクロースを信じない6歳の女の子が、サンタクロースに出会うことで奇跡を信じるようになります。', 'PG', 'DRAMA', '12-SEP-2017');

INSERT INTO TITLE(TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE) VALUES(TITLE_ID_SEQ.NEXTVAL, 'Soda Gang', 'ドラッグの隠し場所を発見した若いカップルが、ギャングに狙われます。', 'NR', 'ACTION', '01-JUN-2017');
