ALTER SESSION SET NLS_LANGUAGE=American;
ALTER SESSION SET NLS_TERRITORY=America;

INSERT INTO MEMBER(MEMBER_ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, PHONE, JOIN_DATE) VALUES(MEMBER_ID_SEQ.NEXTVAL, 'Garmen', 'Velasquez', '283 King Street', 'Seattle', '206-899-6666', '08-MAR-2010');

INSERT INTO MEMBER(MEMBER_ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, PHONE, JOIN_DATE) VALUES(MEMBER_ID_SEQ.NEXTVAL, 'LaDoris', 'Ngao', '5 Modrany', 'Bratislava', '586-355-8882', '08-MAR-2010');

INSERT INTO MEMBER(MEMBER_ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, PHONE, JOIN_DATE) VALUES(MEMBER_ID_SEQ.NEXTVAL, 'Midori', 'Nagayama', '68 Via Centrale', 'Sao Paulo', ' 254-852-5764', '17-JUN-2011');

INSERT INTO MEMBER(MEMBER_ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, PHONE, JOIN_DATE) VALUES(MEMBER_ID_SEQ.NEXTVAL, 'Mark', 'Quick-to-See', '6921 King Way', 'Lagos', '63-559-7777', '12-APR-2012');

INSERT INTO MEMBER(MEMBER_ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, PHONE, JOIN_DATE) VALUES(MEMBER_ID_SEQ.NEXTVAL, 'Audry', 'Ropeburn', '86 Chu Street', 'Hong Kong', '41-559-97', '18-JAN-2013');

INSERT INTO MEMBER(MEMBER_ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, PHONE, JOIN_DATE) VALUES(MEMBER_ID_SEQ.NEXTVAL, 'Molly', 'Urguhart', '3035 Laurier', 'Quebec', '418-542-9988', '18-JAN-2013');
